version: "3.9"

services:
  app:
    image: microwebfrwk:latest
    ports:
      - "8000:8080"
    deploy:
      replicas: 3
      restart_policy:
        condition: on-failure
      placement:
        max_replicas_per_node: 3
    networks:
      - app_net

networks:
  app_net:
    driver: overlay

